# deployments/docker-compose.yml
version: "3.9"
services:
  pys:
    build:
      context: ${ROOT_DIR}/ics-docker
      dockerfile: Dockerfile
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "FactorySimulation.py"]
    container_name: pys
    volumes:
      - ${ROOT_DIR}/src:/src:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      fnet:
        ipv4_address: 192.168.1.31

  plc1:
    build:
      context: ${ROOT_DIR}/ics-docker
      dockerfile: Dockerfile
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "PLC1.py"]
    container_name: plc1
    volumes:
      - ${ROOT_DIR}/src:/src:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.11
      fnet:
        ipv4_address: 192.168.1.11

  hmi1:
    build:
      context: ${ROOT_DIR}/ics-docker
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /src
    entrypoint: ["./start.sh", "HMI1.py"]
    container_name: hmi1
    volumes:
      - ${ROOT_DIR}/src:/src:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.21

  attacker:
    build:
      context: ${ROOT_DIR}/attacker-docker
      dockerfile: Dockerfile
    stdin_open: true
    privileged: true
    tty: true
    working_dir: /src
    entrypoint: ["./start.sh", "Attacker.py"]
    container_name: attacker
    volumes:
      - ${ROOT_DIR}/src:/src:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      wnet:
        ipv4_address: 192.168.0.42

networks:
  wnet:
    driver: bridge
    name: icsnet
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_icsnet
  fnet:
    driver: bridge
    name: phynet
    ipam:
     config:
       - subnet: 192.168.1.0/24
         gateway: 192.168.1.1
    driver_opts:
      com.docker.network.bridge.name: br_phynet
